### ISSUE TITLE
Enable support for cloud

### ISSUE THREAD

**Issue by Just-Insane** [kmoore134/iocage-netdata#3]
Is it possible to enable support for cloud? When trying to claim the node from within the jail there is the following error:

```This agent was built with --disable-cloud and cannot be claimed```

Is there a specific reason the agent was built this way?

It looks like all cloud options where disabled, per https://learn.netdata.cloud/docs/agent/claim#troubleshooting

the API returns:

```
	"cloud-enabled": false,
	"cloud-available": false,
	"agent-claimed": false,
	"aclk-available": false
```

This is for an install running on TrueNAS, if that is relevant.

**Comment by carpshark** [comment]
Looks like there i no progress at all on this topic, any change we could assist?

**Comment by kmoore134** [comment]
I'm not active on this anymore, focus is on the SCALE apps, since iocage is no longer maintained.
